version: "3.8"

services:
  postgres:
    image: ankane/pgvector  # Prebuilt PostgreSQL with pgvector
    container_name: pgvector_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: my_vectors
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
    driver: local
